# Generated by Django 6.0.7 on 2026-08-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('ai', 'AI & ML'), ('backend', 'Backend'), ('other', 'Other')], default='web', max_length=20),
        ),
    ]
