# Generated by Django 6.0.7 on 2026-07-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload a small logo/icon image', null=True, upload_to='skills/'),
        ),
    ]
