# Generated by Django 6.0.7 on 2026-07-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='My Portfolio', max_length=100)),
                ('meta_description', models.CharField(help_text='Shown in search engine results (recommended: under 160 characters)', max_length=300)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords (optional, low SEO impact today)', max_length=300)),
                ('og_image', models.ImageField(blank=True, help_text='Image shown when your site is shared on social media (recommended: 1200x630px)', null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
    ]
