# Generated by Django 6.0.7 on 2026-08-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ai', 'AI'), ('django', 'Django'), ('web', 'Web Development'), ('backend', 'Backend'), ('career', 'Career'), ('devops', 'Tools & DevOps')], default='django', max_length=20),
        ),
    ]
