# Generated by Django 6.0.7 on 2026-07-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('issuing_organization', models.CharField(max_length=150)),
                ('date_earned', models.DateField()),
                ('credential_url', models.URLField(blank=True, help_text='Link to verify this certificate, if available')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
            ],
            options={
                'ordering': ['-date_earned'],
            },
        ),
    ]
